<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Bms.BuildingBlocks.Abstractions\Bms.BuildingBlocks.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Consul" Version="1.7.14.11" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
